default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: portal_development

test:
  <<: *default
  database: portal_test

production:
  <<: *default
  database: portal_production
